import SwiftUI

struct DDLView: View {
    let table: TableInfo
    @Environment(AppState.self) private var appState
    
    @State private var detailedTable: TableInfo?
    @State private var indexes: [SchemaIntrospector.IndexResult] = []
    @State private var isLoading = true
    
    var body: some View {
        Group {
            if isLoading {
                ProgressView("Generating DDL…")
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else if let detailedTable {
                ScrollView {
                    Text(SQLHighlighter.highlight(generateFullDDL(detailedTable, indexes: indexes)))
                        .font(.system(size: 13, design: .monospaced))
                        .textSelection(.enabled)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(16)
                }
            } else {
                ContentUnavailableView("Failed to load DDL", systemImage: "exclamationmark.triangle")
            }
        }
        .task(id: table.id) {
            await loadMetadata()
        }
    }
    
    private func loadMetadata() async {
        isLoading = true
        
        guard let pool = appState.connectionPool,
              let conn = try? await pool.getConnection()
        else {
            isLoading = false
            return
        }

        let introspector = SchemaIntrospector(connection: conn)

        // Fetch columns if missing, and fetch indexes simultaneously
        async let updatedColumns: TableInfo? = appState.loadColumnsForTable(table)
        async let fetchedIndexes: [SchemaIntrospector.IndexResult] =
            (try? await introspector.fetchIndexes(schema: table.schema, table: table.name)) ?? []

        detailedTable = (await updatedColumns) ?? table
        indexes = await fetchedIndexes
        
        isLoading = false
    }

    private func generateFullDDL(_ table: TableInfo, indexes: [SchemaIntrospector.IndexResult]) -> String {
        var ddl = "-- DDL generated by Glint\n"
        ddl += "-- Not all database features are supported. Do not use for backup.\n\n"
        ddl += "-- Table Definition ----------------------------------------------\n\n"
        
        // Don't quote public schema to match Postico cleanliness
        let qSchema = table.schema == "public" ? "" : "\(SQLSanitizer.quoteIdentifier(table.schema))."
        let qTable = "\(qSchema)\(SQLSanitizer.quoteIdentifier(table.name))"
        
        ddl += "CREATE TABLE \(qTable) (\n"
        
        for (i, col) in table.columns.enumerated() {
            ddl += "    \(SQLSanitizer.quoteIdentifier(col.name)) \(col.dataType)"
            if !col.isNullable { ddl += " NOT NULL" }
            if let def = col.defaultValue { ddl += " DEFAULT \(def)" }
            
            // Inline Foreign Key if available
            if let fk = col.foreignKey {
                ddl += " REFERENCES \(SQLSanitizer.quoteIdentifier(fk.referencedTable))(\(SQLSanitizer.quoteIdentifier(fk.referencedColumn)))"
            }
            
            if i < table.columns.count - 1 { ddl += "," }
            ddl += "\n"
        }
        
        let pks = table.columns.filter(\.isPrimaryKey).map { SQLSanitizer.quoteIdentifier($0.name) }
        if !pks.isEmpty {
            if !table.columns.isEmpty {
                ddl.removeLast() // remove \n
                ddl += ",\n"
            }
            ddl += "    PRIMARY KEY (\(pks.joined(separator: ", ")))\n"
        }
        
        ddl += ");\n"
        
        if !indexes.isEmpty {
            ddl += "\n-- Indices -------------------------------------------------------\n\n"
            let nonPrimaryIndexes = indexes.filter { !$0.isPrimary }
            for index in nonPrimaryIndexes {
                ddl += "\(index.definition);\n"
            }
        }
        
        return ddl
    }
}
